#!/usr/bin/env python3
import sys
import math


def solve(a: int, b: int, x: int):
    h = 2 * (b - (x / (a*a)))
    if b < h:
        h = b
        a = 2 * (x / (a*b))
    print(math.degrees(math.atan(h / a)))
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    x = int(next(tokens))  # type: int
    solve(a, b, x)

if __name__ == '__main__':
    main()
