#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):
    ans = 0
    limit = 10 ** 18
    if 0 in A:
        print(0)
        return
    for i, v in enumerate(A):
        if i == 0:
            ans = v 
            continue
        ans *= v
        if ans > limit:
            print(-1)
            return
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
