#!/usr/bin/env python3
import sys


def solve(S: int):
    cnt = 0
    for i in range(len(str(S))):
        for j in range(i + 1, len(str(S))):
            s = str(S)[i:j+1]
            if '0' in s:
                continue
            if not int(str(S)[i:j+1]) % 2019:
                cnt += 1
    print(cnt)
    # cnt = 0
    # l = filter(lambda x: '0' not in str(x), range(2019, 200000, 2019))
    # l = [str(i) for i in l]
    # s = str(S)
    # for i in range(len(s)):
    #     if 5 + i > len(s) - 1:
    #         continue
    #     if s[i:4 + i] in l or s[i:5 + i] in l:
    #         cnt += 1
    # print(cnt)
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = int(next(tokens))  # type: int
    solve(S)

if __name__ == '__main__':
    main()
