#!/usr/bin/env python3
import numpy as np


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    n, k = map(int, input().split())
    a = np.sort(np.array(list(map(int, input().split()))))
    INF = 10 ** 18 + 1
    l, r = INF, -INF
    q = len(a[a == 0])  # len(list(filter(lambda x: x == 0, a)))と同じ
    d = a[a < 0]  # list(filter(lambda:x x < 0, a))と同じ
    e = a[a > 0]  # list(filter(lambda:x x > 0, a))と同じ
    while l - r > 1:
        t = (l + r) // 2
        p = 0
        if t >= 0:
            p += q * n  # すべての0を、他のすべての数(N)と掛け合わせたときの積の数
        # t // e は [t // x for x in e]と同じ
        # 例 >>> np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])
        # array([0, 5, 1, 2])
        p += np.searchsorted(a, t // e, side="right").sum() + (n - np.searchsorted(a, (-t - 1) // (-d), side="right")).sum()
        # a * a <= t は map(lambda x: x <= t, [i * i for i in a])と同じ
        p -= np.count_nonzero(a * a <= t)
        p //= 2
        if p >= k:
            l = t
        else:
            r = t
    print(l)
    return


if __name__ == '__main__':
    main()
