#!/usr/bin/env python3
import sys
from functools import reduce
from operator import add

def solve(a: int, b: int):
    c = a if a <= b else b
    c_str = str(c)
    for _ in range(b - 1 if a <= b else a - 1):
        c_str += str(c)
    print(c_str)
    return

# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    solve(a, b)

if __name__ == '__main__':
    main()
