#!/usr/bin/env python3
import sys
import itertools


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, K = [int(x) for x in input().split()]
    d = []
    A = []
    for i in range(K):
        d.append(input())
        A.append(input().split())
    a = list(set(itertools.chain.from_iterable([list(set(x)) for x in A])))
    print(N - len(a))
    return

if __name__ == '__main__':
    main()
